version: '3.7'

x-db: &db
  MYSQL_HOSTNAME: "${MYSQL_HOSTNAME}"
  MYSQL_PORT: "${MYSQL_PORT}"
  MYSQL_USERNAME: &db_user "${MYSQL_USERNAME}"
  MYSQL_PASSWORD: &db_pass "${MYSQL_PASSWORD}"
  MYSQL_DATABASE: &db_name "${MYSQL_DATABASE}"
  SQL_SERVER_LOCATION: "//${MYSQL_HOSTNAME}:${MYSQL_PORT}"
  SQL_SERVER_USERNAME: *db_user
  SQL_SERVER_PASSWORD: *db_pass
  SQL_SERVER_DATABASE: *db_name

x-ms-env: &ms-env
  << : *db
  SERVER_HOST: &server_host "${SERVER_HOST}"
  SERVER_PORT: &server_port "${SERVER_PORT}"
  MSSOCKET_HOST: *server_host  # for java microservices
  MSSOCKET_PORT: *server_port

x-microservice: &microservice
  restart: always
  depends_on:
    - server
  environment:
    << : *ms-env
  networks:
    - cryptic
    - db

services:
  server:
    container_name: cryptic-server
    image: crypticcp/cryptic-game-server
    restart: always
    environment:
      << : *db
      MSSOCKET_HOST: "${MSSOCKET_HOST}"
      MSSOCKET_PORT: *server_port
      WEBSOCKET_HOST: "${WEBSOCKET_HOST}"
      WEBSOCKET_PORT: "${WEBSOCKET_PORT}"
      HTTP_PORT: "${HTTP_PORT}"
      AUTH_ENABLED: "${AUTH_ENABLED}"
      PRODUCTIVE: "${PRODUCTIVE}"
      LOG_LEVEL: "${LOG_LEVEL}"
      SENTRY_DSN: "${SENTRY_DSN_SERVER}"
      VIRTUAL_HOST: "${VIRTUAL_HOST_SERVER}"
    networks:
      - cryptic
      - db
      - nginx
  ms_device:
    image: crypticcp/cryptic-device
    << : *microservice
    environment:
      << : *ms-env
      DSN: "${SENTRY_DSN_DEVICE}"
  ms_currency:
    image: crypticcp/cryptic-currency
    << : *microservice
    environment:
      << : *ms-env
      DSN: "${SENTRY_DSN_CURRENCY}"
  ms_service:
    image: crypticcp/cryptic-service
    << : *microservice
    environment:
      << : *ms-env
      DSN: "${SENTRY_DSN_SERVICE}"
  ms_inventory:
    image: crypticcp/cryptic-inventory
    << : *microservice
    environment:
      << : *ms-env
      DSN: "${SENTRY_DSN_INVENTORY}"
  ms_network:
    image: crypticcp/cryptic-network
    << : *microservice
    environment:
      << : *ms-env
      LOG_LEVEL: "${LOG_LEVEL}"
      SENTRY_DSN: "${SENTRY_DSN_NETWORK}"
  frontend:
    image: crypticcp/frontend:experimental
    container_name: cryptic-frontend
    restart: always
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST_FRONTEND}"
    networks:
      - nginx

networks:
  cryptic:
  db:
    external:
      name: mariadb
  nginx:
    external: true
