version: '3.7'

x-db: &db
  MYSQL_HOSTNAME: 'db'
  MYSQL_PORT: 3306
  MYSQL_USERNAME: &db_user 'cryptic'
  MYSQL_PASSWORD: &db_pass 'cryptic'
  MYSQL_DATABASE: &db_name 'cryptic'
  SQL_SERVER_LOCATION: '//db:3306'
  SQL_SERVER_USERNAME: *db_user
  SQL_SERVER_PASSWORD: *db_pass
  SQL_SERVER_DATABASE: *db_name

x-ms-env: &ms-env
  << : *db
  SERVER_HOST: &server_host 'server'
  SERVER_PORT: &server_port 1239
  MSSOCKET_HOST: *server_host  # for java microservices
  MSSOCKET_PORT: *server_port

x-microservice: &microservice
  restart: always
  depends_on:
    - server
  environment:
    << : *ms-env
  networks:
    - cryptic
    - db

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: *db_user
      MYSQL_PASSWORD: *db_pass
      MYSQL_DATABASE: *db_name
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - '3306:3306'
    networks:
      - db
  server:
    container_name: cryptic-server
    image: crypticcp/cryptic-game-server:experimental
    restart: always
    depends_on:
      - db
    environment:
      << : *db
      MSSOCKET_HOST: '0.0.0.0'
      MSSOCKET_PORT: *server_port
      WEBSOCKET_HOST: '0.0.0.0'
      WEBSOCKET_PORT: 80
      HTTP_PORT: 8080
      AUTH_ENABLED: 'true'
      PRODUCTIVE: 'false'
      LOG_LEVEL: 'INFO'
      SENTRY_DSN: ''
    networks:
      - cryptic
      - db
    ports:
      - '8080:8080'
      - '80:80'
      - '1239:1239'
  ms_device:
    image: crypticcp/cryptic-device:experimental
    << : *microservice
    environment:
      << : *ms-env
      DSN: ''
  ms_currency:
    image: crypticcp/cryptic-currency:experimental
    << : *microservice
    environment:
      << : *ms-env
      DSN: ''
  ms_service:
    image: crypticcp/cryptic-service:experimental
    << : *microservice
    environment:
      << : *ms-env
      DSN: ''
  ms_inventory:
    image: crypticcp/cryptic-inventory:experimental
    << : *microservice
    environment:
      << : *ms-env
      DSN: ''
  ms_network:
    image: crypticcp/cryptic-network:experimental
    << : *microservice
    environment:
      << : *ms-env
      LOG_LEVEL: 'INFO'
      SENTRY_DSN: ''

networks:
  cryptic:
  db:
