{
 "title": "v2 Statistics (productive)",
 "description": "Statistics of the deployed v2 instance",
 "time": { "from": "now-31d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "User", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  count(*) AS \"count\"\nFROM user"
    }
   ]
  },
  {
   "title": "First Account (last DB Reset)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  UNIX_TIMESTAMP(created) * 1000\nFROM user\nORDER BY created ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "New Users",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  count(*) AS \"count\"\nFROM user\nWHERE\n  $__timeFilter(created)\nGROUP BY day(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "New Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  count(*) AS \"count\"\nFROM user\nWHERE\n  $__timeFilter(created)"
    }
   ]
  },
  { "title": "Morphcoin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total Morphcoins",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currency:MC " } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  sum(amount) / 1000\nFROM currency_wallet"
    }
   ]
  },
  {
   "title": "Total Send Morphcoins",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currency:MC " } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  sum(send_amount)/ 1000\nFROM currency_transaction"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  count(*) AS \"count\"\nFROM currency_transaction"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_stamp,$__interval),\n  count(*)\nFROM currency_transaction\nWHERE\n  $__timeFilter(time_stamp)\nGROUP BY day(time_stamp)\nORDER BY time_stamp"
    }
   ]
  },
  {
   "title": "Stealable Morphcoins",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currency:MC " } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT 0 as time, sum(amount) / 1000\nFROM currency_wallet\nWHERE source_uuid IN (SELECT SUBSTRING(device_file.content, 1, 36)\n                      FROM device_file\n                      WHERE device_file.device IN (SELECT device_device.uuid\n                                                   FROM device_device\n                                                   WHERE device_device.powered_on = true))"
    }
   ]
  },
  {
   "title": "Send Morphcoins",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currency:MC " } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  sum(send_amount)/ 1000\nFROM currency_transaction\nWHERE\n  $__timeFilter(time_stamp)"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  count(*) AS \"count\"\nFROM currency_transaction\nWHERE\n  $__timeFilter(time_stamp)"
    }
   ]
  },
  {
   "title": "Send Morphcoins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currency:MC " } },
   "yaxes": [
    { "format": "currency:MC " }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  sum(send_amount)/ 1000\nFROM currency_transaction\nWHERE\n  $__timeFilter(time_stamp)\nGROUP BY day(time_stamp)\nORDER BY time_stamp"
    }
   ]
  },
  {
   "title": "Morphcoins spend in Hardware Shop",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currency:MC " } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  sum(send_amount)/ 1000\nFROM currency_transaction\nWHERE\n  $__timeFilter(time_stamp)\n  and\n  destination_uuid = \"00000000-0000-0000-0000-000000000000\""
    }
   ]
  },
  {
   "title": "Morphcoins send to other Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currency:MC " } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  sum(send_amount)/ 1000\nFROM currency_transaction\nWHERE\n  $__timeFilter(time_stamp)\n  and\n  destination_uuid <> \"00000000-0000-0000-0000-000000000000\""
    }
   ]
  },
  {
   "title": "Total Wallets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 as \"time\",\n  count(*) AS \"count\"\nFROM currency_wallet"
    }
   ]
  },
  {
   "title": "Total Morphcoins spend in Hardware Shop",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currency:MC " } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  sum(send_amount)/ 1000\nFROM currency_transaction\nWHERE\n  destination_uuid = \"00000000-0000-0000-0000-000000000000\""
    }
   ]
  },
  {
   "title": "Total Morphcoins send to other Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currency:MC " } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  sum(send_amount)/ 1000\nFROM currency_transaction\nWHERE\n  destination_uuid <> \"00000000-0000-0000-0000-000000000000\""
    }
   ]
  },
  {
   "title": "Hackable Wallets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT 0 as time, count(*)\nFROM currency_wallet\nWHERE source_uuid IN (SELECT SUBSTRING(device_file.content, 1, 36)\n                      FROM device_file\n                      WHERE device_file.device IN (SELECT device_device.uuid\n                                                   FROM device_device\n                                                   WHERE device_device.powered_on = true))"
    }
   ]
  },
  { "title": "Miner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Total Miners",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  count(*)\nFROM service_miner"
    }
   ]
  },
  {
   "title": "Stopped Miners",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 as \"time\",\n  count(*) AS \"count\"\nFROM service_miner\nWHERE\n  power = 0"
    }
   ]
  },
  {
   "title": "Started Miners",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 as \"time\",\n  count(*) AS \"count\"\nFROM service_miner\nWHERE\n  power <> 0"
    }
   ]
  },
  {
   "title": "Total Mined Morphcoins",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "currency:MC " } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  (sum(amount + (SELECT sum(currency_transaction.send_amount) FROM currency_transaction WHERE currency_transaction.source_uuid = currency_wallet.source_uuid) - (SELECT sum(send_amount) FROM currency_transaction WHERE currency_transaction.destination_uuid = currency_wallet.source_uuid))) / 1000\nFROM\n  currency_wallet"
    }
   ]
  },
  { "title": "Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Total devices",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 as \"time\",\n  count(*) AS \"count\"\nFROM device_device"
    }
   ]
  },
  {
   "title": "Online devices",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 as \"time\",\n  count(*) AS \"count\"\nFROM device_device\nWHERE\n  powered_on = TRUE"
    }
   ]
  },
  {
   "title": "Total files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT 0 as time, count(*) FROM device_file"
    }
   ]
  }
 ]
}